-- Copyright 2007 GQR Solutions. All rights reserved.
-- PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
--
-- Cmp History
--

DROP SEQUENCE BSCMPHSEQ IF EXISTS;

CREATE SEQUENCE BSCMPHSEQ AS INTEGER
START WITH 0 INCREMENT BY 1;

DROP TABLE BSCMPH IF EXISTS;

CREATE CACHED TABLE BSCMPH(
	Cmp	CHAR(10),
	HisSeq	INT NOT NULL,
	HisDte	DATETIME,
	HisAct	CHAR(1),
	HisRmk	VARCHAR(200),
-- COPY FROM BSCMP START
	Nme	VARCHAR(30),
	RegNo	VARCHAR(15),
	PriAdd	INT,
	PriCnt	INT,
	WebSte	VARCHAR(50),
	CurCde	CHAR(5),
-- COPY FROM BSCMP END
	PRIMARY KEY(Cmp, HisSeq));
	
DROP SEQUENCE BSCMPAHSEQ IF EXISTS;

CREATE SEQUENCE BSCMPAHSEQ AS INTEGER
START WITH 0 INCREMENT BY 1;

DROP TABLE BSCMPAH IF EXISTS;

CREATE CACHED TABLE BSCMPAH(
	Cmp     CHAR(10),
	HisSeq	INT NOT NULL,
	HisDte	DATETIME,
	HisAct	CHAR(1),
	HisRmk	VARCHAR(200),
-- COPY FROM BSCMPA START
	Seq	INT,
	Add1	VARCHAR(60),
	Add2	VARCHAR(60),
	City	VARCHAR(30),
	ZipCde	CHAR(5),
	Stte	VARCHAR(30),
	Ctry	VARCHAR(30),
	Tel	VARCHAR(15),
	Fax	VARCHAR(15),
	Remark	VARCHAR(200),
-- COPY FROM BSCMPA END
	PRIMARY KEY(Cmp, HisSeq));

DROP SEQUENCE BSCMPCHSEQ IF EXISTS;

CREATE SEQUENCE BSCMPCHSEQ AS INTEGER
START WITH 0 INCREMENT BY 1;

DROP TABLE BSCMPCH IF EXISTS;

CREATE CACHED TABLE BSCMPCH(
	Cmp	CHAR(10),
	HisSeq	INT NOT NULL,
	HisDte	DATETIME,
	HisAct	CHAR(1),
	HisRmk	VARCHAR(200),
-- COPY FROM BSCMPC START
	Seq	INT,
	FstNme	VARCHAR(30),
	LstNme	VARCHAR(30),
	Title	VARCHAR(30),
	Tel	VARCHAR(15),
	Fax	VARCHAR(15),
        Mobile  VARCHAR(15),
	Email	VARCHAR(50),
	Remark	VARCHAR(200),
-- COPY FROM BSCMPC END
	PRIMARY KEY(Cmp, HisSeq));

DROP SEQUENCE BSCFGHSEQ IF EXISTS;

CREATE SEQUENCE BSCFGHSEQ AS INTEGER
START WITH 0 INCREMENT BY 1;

DROP TABLE BSCFGH IF EXISTS;

CREATE CACHED TABLE BSCFGH(
	Cmp	CHAR(10),
	HisSeq	INT NOT NULL,
	HisDte	DATETIME,
	HisAct	CHAR(1),
	HisRmk	VARCHAR(200),
-- COPY FROM BSCFG START
	LstNumQtt	INT,
	LstNumInv	INT,
	LstNumRcp	INT,
	LstNumPor	INT,
	LstNumPiv	INT,
	NumDgtsQtt	INT,
	NumDgtsInv	INT,
	NumDgtsRcp	INT,
	NumDgtsPor	INT,
	NumDgtsPiv	INT,
	PrfxQtt         CHAR(10),
	PrfxInv         CHAR(10),
	PrfxRcp         CHAR(10),
	PrfxPor         CHAR(10),
	PrfxPiv         CHAR(10),
	DfltTrmQtt	CHAR(20),
	DfltTrmInv	CHAR(20),
	DfltTrmRcp	CHAR(20),
	PrtFmtQtt	CHAR(1),
	PrtFmtInv	CHAR(1),
	PrtFmtRcp	CHAR(1),
	PrtFmtPor	CHAR(1),
	PrtFmtPiv	CHAR(1),
-- COPY FROM BSCFG END
	PRIMARY KEY(Cmp, HisSeq));
	