-- Copyright 2007 GQR Solutions. All rights reserved.
-- PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
--
-- Sales Invoice
--

DROP TABLE BSINV IF EXISTS;

CREATE CACHED TABLE BSINV(
	Cmp		CHAR(10),
	InvNo		CHAR(20),
	Cus		CHAR(10),
	InvDte		DATETIME,
	DueDte		DATETIME,
	RefNum  	VARCHAR(20),
	Remark		VARCHAR(200),
	Status 		CHAR(1),
        TtlGrsAmt       DECIMAL,
        TtlAmt          DECIMAL,
	PRIMARY KEY(Cmp, InvNo));

DROP TABLE BSINVD IF EXISTS;

CREATE CACHED TABLE BSINVD(
	Cmp	CHAR(10),
	InvNo	CHAR(20),
	Itm	CHAR(10),
	Price	DECIMAL,
	Qty	INT,
	TtlAmt	DECIMAL,
	PRIMARY KEY(Cmp, InvNo, Itm));

DROP TABLE BSINVA IF EXISTS;

CREATE CACHED TABLE BSINVA(
	Cmp	CHAR(10),
	InvNo	CHAR(20),
	Add1	VARCHAR(60),
	Add2	VARCHAR(60),
	City	VARCHAR(30),
	ZipCde	CHAR(5),
	Stte	VARCHAR(30),
	Ctry	VARCHAR(30),
	Tel	VARCHAR(15),
	Fax	VARCHAR(15),
	Remark	VARCHAR(200),
	PRIMARY KEY(Cmp, InvNo));

DROP TABLE BSINVC IF EXISTS;

CREATE CACHED TABLE BSINVC(
	Cmp	CHAR(10),
	InvNo	CHAR(20),
	FstNme	VARCHAR(30),
	LstNme	VARCHAR(30),
	Title	VARCHAR(30),
	Tel	VARCHAR(15),
	Fax	VARCHAR(15),
	Mobile	VARCHAR(15),
	Email	VARCHAR(50),
	Remark	VARCHAR(200),
	PRIMARY KEY(Cmp, InvNo));
	
DROP TABLE BSINVJ IF EXISTS;

CREATE CACHED TABLE BSINVJ(
	Cmp	CHAR(10),
	InvNo	CHAR(20),
	Seq	INT,
	Adj	CHAR(10),
	Nme	CHAR(30),
	Typ	CHAR(1),
	Prio	INT,
	Amt	DECIMAL,
	EffAmt	DECIMAL,
	OpenAmt	DECIMAL,
	NewAmt	DECIMAL,
	PRIMARY KEY(Cmp, InvNo, Seq));

DROP TABLE BSINVR IF EXISTS;

CREATE CACHED TABLE BSINVR(
	Cmp	CHAR(10),
	InvNo	CHAR(20),
	Seq	INT,
	Text	CHAR(60),
	PRIMARY KEY(Cmp, InvNo, Seq));

