-- Copyright 2007 GQR Solutions. All rights reserved.
-- PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
--
-- purchase item history tables
--

DROP SEQUENCE BSPIHSEQ IF EXISTS;

CREATE SEQUENCE BSPIHSEQ AS INTEGER
START WITH 0 INCREMENT BY 1;

DROP TABLE BSPIH IF EXISTS;

CREATE CACHED TABLE BSPIH(
	Cmp	CHAR(10),
	HisSeq	INT NOT NULL,
	HisDte	DATETIME,
	HisAct	CHAR(1),
	HisRmk	VARCHAR(200),
-- COPY FROM BSPI START
	Itm	CHAR(10),
	Nme	CHAR(60),
	Status 	CHAR(1),
-- COPY FROM BSPI END
	PRIMARY KEY(Cmp, HisSeq));

DROP SEQUENCE BSPIPHSEQ IF EXISTS;

CREATE SEQUENCE BSPIPHSEQ AS INTEGER
START WITH 0 INCREMENT BY 1;

DROP TABLE BSPIPH IF EXISTS;

CREATE CACHED TABLE BSPIPH(
	Cmp	CHAR(10),
	HisSeq	INT NOT NULL,
	HisDte	DATETIME,
	HisAct	CHAR(1),
	HisRmk	VARCHAR(200),
-- COPY FROM BSPIP START
	Itm	CHAR(10),
	Sup	CHAR(10),
	Price	DECIMAL,
	Status	CHAR(1),
	Remark	CHAR(200),
-- COPY FROM BSPIP END
	PRIMARY KEY(Cmp, HisSeq));
