-- Copyright 2007 GQR Solutions. All rights reserved.
-- PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
--
-- purchase special instruction tables
--

DROP TABLE BSPSI IF EXISTS;

CREATE CACHED TABLE BSPSI(
	Cmp	CHAR(10),
	SpcInst	CHAR(10),
	Nme	CHAR(30),
	Status 	CHAR(1),
	PRIMARY KEY(Cmp, SpcInst));

DROP TABLE BSPSID IF EXISTS;

CREATE CACHED TABLE BSPSID(
	Cmp	CHAR(10),
	SpcInst	CHAR(10),
	Seq	INT,
	Text	VARCHAR(80),
	PRIMARY KEY(Cmp, SpcInst, Seq));

-- History tables

DROP SEQUENCE BSPSIHSEQ IF EXISTS;

CREATE SEQUENCE BSPSIHSEQ AS INTEGER
START WITH 0 INCREMENT BY 1;

DROP TABLE BSPSIH IF EXISTS;

CREATE CACHED TABLE BSPSIH(
	Cmp	CHAR(10),
	HisSeq	INT NOT NULL,
	HisDte	DATETIME,
	HisAct	CHAR(1),
	HisRmk	VARCHAR(200),
-- COPY FROM BSPSI START
	SpcInst	CHAR(10),
	Nme	CHAR(30),
	Status 	CHAR(1),
-- COPY FROM BSPSI END
	PRIMARY KEY(Cmp, HisSeq));

DROP SEQUENCE BSPSIDHSEQ IF EXISTS;

CREATE SEQUENCE BSPSIDHSEQ AS INTEGER
START WITH 0 INCREMENT BY 1;

DROP TABLE BSPSIDH IF EXISTS;

CREATE CACHED TABLE BSPSIDH(
	Cmp	CHAR(10),
	HisSeq	INT NOT NULL,
	HisDte	DATETIME,
	HisAct	CHAR(1),
	HisRmk	VARCHAR(200),
-- COPY FROM BSPSID START
	SpcInst	CHAR(10),
	Seq	INT,
	Text	VARCHAR(80),
-- COPY FROM BSPSID END
	PRIMARY KEY(Cmp, HisSeq));
