-- Copyright 2007 GQR Solutions. All rights reserved.
-- PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
--
-- sales item history tables
--

DROP SEQUENCE BSSIHSEQ IF EXISTS;

CREATE SEQUENCE BSSIHSEQ AS INTEGER
START WITH 0 INCREMENT BY 1;

DROP TABLE BSSIH IF EXISTS;

CREATE CACHED TABLE BSSIH(
	Cmp	CHAR(10),
	HisSeq	INT NOT NULL,
	HisDte	DATETIME,
	HisAct	CHAR(1),
	HisRmk	VARCHAR(200),
-- COPY FROM BSSI START
	Itm	CHAR(10),
	Nme	CHAR(30),
	Price	DECIMAL,
	Status 	CHAR(1),
-- COPY FROM BSSI END
	PRIMARY KEY(Cmp, HisSeq));

DROP SEQUENCE BSSIDHSEQ IF EXISTS;

CREATE SEQUENCE BSSIDHSEQ AS INTEGER
START WITH 0 INCREMENT BY 1;

DROP TABLE BSSIDH IF EXISTS;

CREATE CACHED TABLE BSSIDH(
	Cmp	CHAR(10),
	HisSeq	INT NOT NULL,
	HisDte	DATETIME,
	HisAct	CHAR(1),
	HisRmk	VARCHAR(200),
-- COPY FROM BSSI START
	Itm	CHAR(10),
	Seq	INT,
	Text	CHAR(60),
-- COPY FROM BSSI END
	PRIMARY KEY(Cmp, HisSeq));
