-- Copyright 2007 GQR Solutions. All rights reserved.
-- PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
--
-- supplier history tables
--

DROP SEQUENCE BSSUPHSEQ IF EXISTS;

CREATE SEQUENCE BSSUPHSEQ AS INTEGER
START WITH 0 INCREMENT BY 1;

DROP TABLE BSSUPH IF EXISTS;

CREATE CACHED TABLE BSSUPH(
	Cmp	CHAR(10),
	HisSeq	INT NOT NULL,
	HisDte	DATETIME,
	HisAct	CHAR(1),
	HisRmk	VARCHAR(200),
-- COPY FROM BSSUP START
	Sup	CHAR(10),
	Nme	VARCHAR(30),
	Typ	CHAR(1),
	RegNo	VARCHAR(15),
	PriAdd	INT,
	PriCnt	INT,
	WebSte	VARCHAR(50),
	Status	CHAR(1),
	Remark	VARCHAR(200),
-- COPY FROM BSSUP END
	PRIMARY KEY(Cmp, HisSeq));

DROP SEQUENCE BSSUPAHSEQ IF EXISTS;

CREATE SEQUENCE BSSUPAHSEQ AS INTEGER
START WITH 0 INCREMENT BY 1;

DROP TABLE BSSUPAH IF EXISTS;

CREATE CACHED TABLE BSSUPAH(
	Cmp	CHAR(10),
	HisSeq	INT NOT NULL,
	HisDte	DATETIME,
	HisAct	CHAR(1),
	HisRmk	VARCHAR(200),
-- COPY FROM BSSUPA START
	Sup	CHAR(10),
	Seq	INT,
	Add1	VARCHAR(60),
	Add2	VARCHAR(60),
	City	VARCHAR(30),
	ZipCde	CHAR(5),
	Stte	VARCHAR(30),
	Ctry	VARCHAR(30),
	Tel	VARCHAR(15),
	Fax	VARCHAR(15),
	Remark	VARCHAR(200),
-- COPY FROM BSSUPA END
	PRIMARY KEY(Cmp, HisSeq));

DROP SEQUENCE BSSUPCHSEQ IF EXISTS;

CREATE SEQUENCE BSSUPCHSEQ AS INTEGER
START WITH 0 INCREMENT BY 1;

DROP TABLE BSSUPCH IF EXISTS;

CREATE CACHED TABLE BSSUPCH(
	Cmp	CHAR(10),
	HisSeq	INT NOT NULL,
	HisDte	DATETIME,
	HisAct	CHAR(1),
	HisRmk	VARCHAR(200),
-- COPY FROM BSSUPC START
	Sup	CHAR(10),
	Seq	INT,
	FstNme	VARCHAR(30),
	LstNme	VARCHAR(30),
	Title	VARCHAR(30),
	Tel	VARCHAR(15),
	Fax	VARCHAR(15),
	Mobile	VARCHAR(15),
	Email	VARCHAR(50),
	Remark	VARCHAR(200),
-- COPY FROM BSSUPC END
	PRIMARY KEY(Cmp, HisSeq));
