-- Copyright 2007 GQR Solutions. All rights reserved.
-- PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
--
-- initdb.100.sql - initialize new database
--

DROP TABLE PFDB IF EXISTS;

CREATE CACHED TABLE PFDB(
  Typ CHAR(1) NOT NULL,
  Version INT NOT NULL,
  PRIMARY KEY(Typ));

DROP TABLE PFACT IF EXISTS;

CREATE CACHED TABLE PFACT(
  AccTyp CHAR(1) NOT NULL,
  Nme CHAR(20) NOT NULL,
  Lang VARCHAR(100) NOT NULL,
  OrderFull INT,
  OrderBS INT,
  OrderPL INT,
  PRIMARY KEY(AccTyp));

DROP TABLE PFUSR IF EXISTS;

CREATE CACHED TABLE PFUSR(
  Id VARCHAR(100) NOT NULL,
  FstNme VARCHAR(50),
  LstNme VARCHAR(50),
  Email VARCHAR(100),
  Dob DATE,
  Gender CHAR(1) NOT NULL,
  Career VARCHAR(100),
  Ind VARCHAR(100),
  MrtSts CHAR(1) NOT NULL,
  Add1 VARCHAR(100),
  Add2 VARCHAR(100),
  City VARCHAR(100),
  ZipCde CHAR(5),
  State VARCHAR(100),
  Ctry VARCHAR(100),
  PRIMARY KEY(Id));

DROP TABLE PFACC IF EXISTS;

CREATE CACHED TABLE PFACC(
  Id VARCHAR(100) NOT NULL,
  Acc VARCHAR(20) NOT NULL,
  Nme VARCHAR(100) NOT NULL,
  AccTyp CHAR(1) NOT NULL,
  AccGrp CHAR(20) NOT NULL,
  SysTyp CHAR(1) NOT NULL,
  BalAmt DECIMAL(12, 4) NOT NULL,
  BalDte DATETIME NOT NULL,
  BalTxnId INT NOT NULL,
  Remark VARCHAR(100),
  PRIMARY KEY(Id, Acc));

DROP SEQUENCE PFTXNSEQ IF EXISTS;

CREATE SEQUENCE PFTXNSEQ AS INTEGER 
START WITH 0 INCREMENT BY 1;

DROP TABLE PFTXN IF EXISTS;

CREATE CACHED TABLE PFTXN(
  Id VARCHAR(100) NOT NULL,
  TxnId INT NOT NULL,
  TxnTyp CHAR(1) NOT NULL,
  TxnDte DATETIME NOT NULL,
  FrmAcc VARCHAR(20) NOT NULL,
  ToAcc VARCHAR(20) NOT NULL,
  UsrAmt DECIMAL(12, 4) NOT NULL,
  TxnAmt DECIMAL(12, 4) NOT NULL,
  RefNo VARCHAR(50),
  Dsc VARCHAR(200),
  Remark VARCHAR(100),
  PRIMARY KEY (Id, TxnId));

DROP TABLE PFCFG IF EXISTS;

CREATE CACHED TABLE PFCFG(
  Id VARCHAR(100) NOT NULL,
  MainAccLstTyp CHAR(1) NOT NULL,
  CapAcc VARCHAR(20) NOT NULL,
  IncAcc VARCHAR(20) NOT NULL,
  RtIncAcc VARCHAR(20) NOT NULL,
  DefRecAcc VARCHAR(20) NOT NULL,
  CurTxnId INT DEFAULT 0,
  PRIMARY KEY(Id));

DROP TABLE PFTXNE IF EXISTS;

CREATE CACHED TABLE PFTXNE(
  Id VARCHAR(100) NOT NULL,
  TxnId INT NOT NULL, 
  Acc VARCHAR(20) NOT NULL,
  TxnDte DATETIME NOT NULL,
  Dbt DECIMAL(12, 4) NOT NULL,
  Crt DECIMAL(12, 4) NOT NULL,
  Amt DECIMAL(12, 4) NOT NULL,
  AcuAmt DECIMAL(12, 4) NOT NULL,
  YearAcuAmt DECIMAL(12, 4) NOT NULL,
  MonthAcuAmt DECIMAL(12, 4) NOT NULL,
  PRIMARY KEY(Id, TxnId, Acc));

DROP TABLE PFACCM IF EXISTS;

CREATE CACHED TABLE PFACCM(
  Id VARCHAR(100) NOT NULL,
  Acc VARCHAR(20) NOT NULL,
  Year INT NOT NULL,
  Month INT NOT NULL,
  TxnCnt INT NOT NULL,
  TtlDbt DECIMAL(12, 4) NOT NULL,
  TtlCrt DECIMAL(12, 4) NOT NULL,
  TtlAmt DECIMAL(12, 4) NOT NULL,
  PRIMARY KEY(Id, Acc, Year, Month));

DROP TABLE PFACCY IF EXISTS;

CREATE CACHED TABLE PFACCY(
  Id VARCHAR(100) NOT NULL,
  Acc VARCHAR(20) NOT NULL,
  Year INT NOT NULL,
  TxnCnt INT NOT NULL,
  TtlDbt DECIMAL(12, 4) NOT NULL,
  TtlCrt DECIMAL(12, 4) NOT NULL,
  TtlAmt DECIMAL(12, 4) NOT NULL,
  PRIMARY KEY(id, acc, year));

DROP SEQUENCE PFACCTSEQ IF EXISTS;

CREATE SEQUENCE PFACCTSEQ AS INTEGER
START WITH 0 INCREMENT BY 1;

DROP TABLE PFACCT IF EXISTS;

CREATE CACHED TABLE PFACCT(
  Id VARCHAR(100) NOT NULL,
  Seq INT NOT NULL, 
  Acc VARCHAR(100),
  Nme VARCHAR(100),
  AccTyp CHAR(100),
  BalAmt VARCHAR(100),
  BalDte VARCHAR(100),
  Remark VARCHAR(100),
  PRIMARY KEY(id, seq));

DROP SEQUENCE PFTXNTSEQ IF EXISTS;

CREATE SEQUENCE PFTXNTSEQ AS INTEGER
START WITH 0 INCREMENT BY 1;

DROP TABLE PFTXNT IF EXISTS;

CREATE CACHED TABLE PFTXNT(
  Id VARCHAR(100) NOT NULL,
  Seq INT NOT NULL,
  TxnTyp CHAR(1),
  TxnDte VARCHAR(100),
  FrmAcc VARCHAR(20),
  ToAcc VARCHAR(20),
  UsrAmt VARCHAR(100),
  RefNo VARCHAR(50),
  Dsc VARCHAR(200),
  Remark VARCHAR(100),
  PRIMARY KEY (id, seq));

DROP SEQUENCE PFUSRHSEQ IF EXISTS;

CREATE SEQUENCE PFUSRHSEQ AS INTEGER
START WITH 0 INCREMENT BY 1;

DROP TABLE PFUSRH IF EXISTS;

CREATE CACHED TABLE PFUSRH(
  HisSeq INT NOT NULL,
  HisDte DATETIME,
  HisAct CHAR(1),
  HisRmk VARCHAR(200),
  Id VARCHAR(100),
  FstNme VARCHAR(50),
  LstNme VARCHAR(50),
  Email VARCHAR(100),
  Dob DATE,
  Gender CHAR(1),
  Career VARCHAR(100),
  Ind VARCHAR(100),
  MrtSts CHAR(1),
  Add1 VARCHAR(100),
  Add2 VARCHAR(100),
  City VARCHAR(100),
  ZipCde CHAR(5),
  State VARCHAR(100),
  Ctry VARCHAR(100),
  PRIMARY KEY(hisSeq));

DROP SEQUENCE PFCFGHSEQ IF EXISTS;

CREATE SEQUENCE PFCFGHSEQ AS INTEGER
START WITH 0 INCREMENT BY 1;

DROP TABLE PFCFGH IF EXISTS;

CREATE CACHED TABLE PFCFGH(
  Id VARCHAR(100) NOT NULL,
  HisSeq INT NOT NULL,
  HisDte DATETIME,
  HisAct CHAR(1),
  HisRmk VARCHAR(200),
  MainAccLstTyp CHAR(1) NOT NULL,
  CapAcc VARCHAR(20) NOT NULL,
  IncAcc VARCHAR(20) NOT NULL,
  RtIncAcc VARCHAR(20) NOT NULL,
  DefRecAcc VARCHAR(20) NOT NULL,
  PRIMARY KEY(Id, HisSeq));

DROP SEQUENCE PFACCHSEQ IF EXISTS;

CREATE SEQUENCE PFACCHSEQ AS INTEGER
START WITH 0 INCREMENT BY 1;

DROP TABLE PFACCH IF EXISTS;

CREATE CACHED TABLE PFACCH(
  Id VARCHAR(100) NOT NULL,
  HisSeq INT NOT NULL,
  HisDte DATETIME,
  HisAct CHAR(1),
  HisRmk VARCHAR(200),
  Acc VARCHAR(20),
  Nme VARCHAR(100),
  AccTyp CHAR(1),
  AccGrp CHAR(20),
  SysTyp CHAR(1),
  BalAmt DECIMAL(12, 4),
  BalDte DATETIME,
  BalTxnId INT,
  Remark VARCHAR(100),
  PRIMARY KEY(Id, HisSeq));

DROP SEQUENCE PFTXNHSEQ IF EXISTS;

CREATE SEQUENCE PFTXNHSEQ AS INTEGER
START WITH 0 INCREMENT BY 1;

DROP TABLE PFTXNH IF EXISTS;

CREATE CACHED TABLE PFTXNH(
  Id VARCHAR(100) NOT NULL,
  HisSeq INT NOT NULL,
  HisDte DATETIME,
  HisAct CHAR(1),
  HisRmk VARCHAR(200),
  TxnId INT,
  TxnTyp CHAR(1),
  TxnDte DATETIME,
  FrmAcc VARCHAR(20),
  ToAcc VARCHAR(20),
  UsrAmt DECIMAL(12, 4),
  TxnAmt DECIMAL(12, 4),
  RefNo VARCHAR(50),
  Dsc VARCHAR(200),
  Remark VARCHAR(100),
  PRIMARY KEY (Id, HisSeq));
  
INSERT INTO PFACT(AccTyp, Nme, Lang, OrderFull, OrderBS, OrderPL) 
VALUES('A', 'Asset',     'AccTyp.A', 30, 10, 0);

INSERT INTO PFACT(AccTyp, Nme, Lang, OrderFull, OrderBS, OrderPL) 
VALUES('L', 'Liability', 'AccTyp.L', 40, 20, 0);

INSERT INTO PFACT(AccTyp, Nme, Lang, OrderFull, OrderBS, OrderPL) 
VALUES('C', 'Capital',   'AccTyp.C', 50, 30, 0);

INSERT INTO PFACT(AccTyp, Nme, Lang, OrderFull, OrderBS, OrderPL) 
VALUES('I', 'Income',    'AccTyp.I', 10, 0, 10);

INSERT INTO PFACT(AccTyp, Nme, Lang, OrderFull, OrderBS, OrderPL) 
VALUES('E', 'Expenses',  'AccTyp.E', 20, 0, 20);

INSERT INTO PFDB(Typ, Version) VALUES('A', 100);
