name: Test on Commit on non-master
on:
  push:
    branches:
      - "*"
      - "!master"
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: "8"
          distribution: "adopt"
      - name: Build with Ant
        run: ant
      - name: deploy jar
        run: . .github/workflows/deploy_jar.sh
        env:
          CODESIGN_STORE: ${{ secrets.CODESIGN_STORE }}
          CODESIGN_STORE_PASSWORD: ${{ secrets.CODESIGN_STORE_PASSWORD }}
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install
      - run: npx docusaurus build
      - uses: actions/upload-artifact@v3
        with:
          name: build
          path: build
